# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/brian/projects/cpp/plox/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/brian/projects/cpp/plox

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/brian/projects/cpp/plox/CMakeFiles /home/brian/projects/cpp/plox/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/brian/projects/cpp/plox/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named plox_repl

# Build rule for target.
plox_repl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 plox_repl
.PHONY : plox_repl

# fast build rule for target.
plox_repl/fast:
	$(MAKE) -f CMakeFiles/plox_repl.dir/build.make CMakeFiles/plox_repl.dir/build
.PHONY : plox_repl/fast

#=============================================================================
# Target rules for targets named plox

# Build rule for target.
plox: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 plox
.PHONY : plox

# fast build rule for target.
plox/fast:
	$(MAKE) -f CMakeFiles/plox.dir/build.make CMakeFiles/plox.dir/build
.PHONY : plox/fast

# target to build an object file
Lox.o:
	$(MAKE) -f CMakeFiles/plox.dir/build.make CMakeFiles/plox.dir/Lox.o
.PHONY : Lox.o

# target to preprocess a source file
Lox.i:
	$(MAKE) -f CMakeFiles/plox.dir/build.make CMakeFiles/plox.dir/Lox.i
.PHONY : Lox.i

# target to generate assembly for a file
Lox.s:
	$(MAKE) -f CMakeFiles/plox.dir/build.make CMakeFiles/plox.dir/Lox.s
.PHONY : Lox.s

# target to build an object file
Token.o:
	$(MAKE) -f CMakeFiles/plox.dir/build.make CMakeFiles/plox.dir/Token.o
.PHONY : Token.o

# target to preprocess a source file
Token.i:
	$(MAKE) -f CMakeFiles/plox.dir/build.make CMakeFiles/plox.dir/Token.i
.PHONY : Token.i

# target to generate assembly for a file
Token.s:
	$(MAKE) -f CMakeFiles/plox.dir/build.make CMakeFiles/plox.dir/Token.s
.PHONY : Token.s

# target to build an object file
main.o:
	$(MAKE) -f CMakeFiles/plox_repl.dir/build.make CMakeFiles/plox_repl.dir/main.o
.PHONY : main.o

# target to preprocess a source file
main.i:
	$(MAKE) -f CMakeFiles/plox_repl.dir/build.make CMakeFiles/plox_repl.dir/main.i
.PHONY : main.i

# target to generate assembly for a file
main.s:
	$(MAKE) -f CMakeFiles/plox_repl.dir/build.make CMakeFiles/plox_repl.dir/main.s
.PHONY : main.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... plox_repl"
	@echo "... plox"
	@echo "... Lox.o"
	@echo "... Lox.i"
	@echo "... Lox.s"
	@echo "... Token.o"
	@echo "... Token.i"
	@echo "... Token.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

